### ISSUE TITLE
use W_ReleaseLumpNum()/Name() instead of Z_ChangeTag()

### ISSUE THREAD

**Issue by fabiangreffrath** [fabiangreffrath/crispy-doom#430]
There is a warning in `w_wad.c` not to use `Z_ChangeTag()` directly, but use `W_ReleaseLumpNum()` instead. However, there are a few occasions where the former is used in Crispy's code, especially in code taken from other source ports. All of these should get replaced with calls to the recommended functions.

https://github.com/fabiangreffrath/crispy-doom/blob/master/src/w_wad.c#L393

**Comment by fabiangreffrath** [comment]
*hint* this is low-hanging fruit for contributors *hint*

**Comment by turol** [comment]
Github has some kind of builtin support for "help needed" and "good first issue" tags. You should try those.

**Comment by WSSDude** [comment]
I hope I did good. It compiles and plays without issues so I guess its fine :)

**Comment by fabiangreffrath** [comment]
Fixed now

**Comment by WSSDude** [comment]
Just forgot to ask one thing - this is purely Doom repo if I understood correctly. Why are there files for Hexen, Heretic,...?
I did not fix these in those, as I assumed they are not used. Other question arises though if my assumptions are correct - why have then in a source tree then? They are effectively garbage at this moment if they are not maintained and compiled anyway.

**Comment by WSSDude** [comment]
Made separate issue for this so it is not hidden inside here #433
