### ISSUE TITLE
crispy-midiproc.exe sets off Windows Defender

### ISSUE THREAD

**Issue by KawaiiDinosaur** [fabiangreffrath/crispy-doom#560]
Windows 10 version 1909

Windows Defender detects that **crispy-midiproc.exe** is infected by "Trojan:Win32/Occamy.C" and puts the files in quarantine. I can't say if it's a false alert or not. Binaries downloaded from http://latest.chocolate-doom.org/.

**Comment by fabiangreffrath** [comment]
I know, thanks! The issue is currently discussed on the Doomworld forum. Most likely a false positive:

https://www.doomworld.com/forum/topic/67168-crispy-doom-572-update-mar-13-2020/?page=55&tab=comments#comment-2100331

**Comment by d9d6ka** [comment]
Just checked latest binaries from http://latest.chocolate-doom.org/, Windows Defender shows no threats.
But while checking v5.7.2 Windows Defender does.

**Comment by QuartzSTQ** [comment]
This seems to be fixed now, I recall reporting the 5.7.2 files for midiproc and setup myself, and while they fixed those, the master builds continued to be "infected". However, recent git builds and 5.7.2 now don't give off anything with the latest definitions.

Just to make sure, I rescanned the builds using VirusTotal as well.

Latest master build (20200408): [zip](https://www.virustotal.com/gui/file/a74621eb9bd2d831f7a33d7adfc2e366d5bdd08b8169e6cfd872e6bd12db1bbb/detection) [crispy-doom](https://www.virustotal.com/gui/file/e138b7e99b7c128b0f60f14e55af31c2df48bda27f9300748586a058be4a5764/detection) [setup](https://www.virustotal.com/gui/file/c841e785b70d26605ac3913b82138bab05915ad0d39e075f2d5678f37427807a/detection) [midiproc](https://www.virustotal.com/gui/file/0399781e2ffeb57b924ba14a8547550038200083265f69eeed3640a8f378a74c/detection)

Latest release (5.7.2): [zip](https://www.virustotal.com/gui/file/e2b6cc843f0d7e5363406ce07482baadeab5e9faed3e50df5e2e52d2accfc4d6/detection) [crispy-doom](https://www.virustotal.com/gui/file/ef575174d0b9cd4a40424a483aece316bd44fca228c764f5ab209c4ec9ba3044/detection) [setup](https://www.virustotal.com/gui/file/3d67056ca155e2cd86386fa7a1cd7e46bcacacae1cb1a11f3b6c4ef5f7f2ce6b/detection) [midiproc](https://www.virustotal.com/gui/file/10826414ee28b2eddbf6746c6fb1df897f6a3fb9d8fba33b253c77923e817d5e/detection)

As you may notice some stuff is still detected by "Microsoft", but I think VirusTotal might just not be using the latest definitions, as on my machine with the newest definitions it doesn't detect anything.

**Comment by fabiangreffrath** [comment]
Should be fixed with the 5.8.0 release.

**Comment by d9d6ka** [comment]
Problem still occurs with 5.8.0 and Windows Defender. VirusTotal shows some alerts as well.

**Comment by fabiangreffrath** [comment]
Apparently there is not much that I can do about this, as I don't even build the binaries myself.
